### PR TITLE
[Issue-514] Catch the exact exception for checkTransactionStatus

### LINKED ISSUE #514: Catch the exact exception for checkTransactionStatus
**Problem description**
In https://github.com/pravega/pravega/pull/6028, the exception thrown has changed from a general `RuntimeException` to a `StatusRuntimeException`, we need to update the Pravega client version and make the change in the transactional writer.

**Problem location**
`FlinkPravegaWriter`

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by thekingofcity**
Signed-off-by: zhongle.wang <zhongle_wang@dell.com>

**Change log description**

In pravega/pravega#6028, the exception thrown has changed from a general `RuntimeException` to a `StatusRuntimeException`, we need to update the Pravega client version and make the change in the transactional writer.

**Purpose of the change**

Fixes #514 

**What the code does**

Change `RuntimeException` to `StatusRuntimeException`.

**How to verify it**

`./gradlew clean build` passes.

### CODE REVIEW

File: src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java [hunk 1]
```diff
@@ -82,8 +83,13 @@
     // ------------------------------------------------------------------------
     protected void initializeReaderGroup(String readerGroupName, String readerGroupScope, ClientConfig clientConfig) {
         readerGroupManager = ReaderGroupManager.withScope(readerGroupScope, clientConfig);
-        readerGroupManager.createReaderGroup(readerGroupName, readerGroupConfig);
-        readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
+        try {
+            readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
+            readerGroup = readerGroupManager.getReaderGroup(readerGroupName);
```
Comment (crazyzhou) [inline src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java:88]: Redundant call here

**Review by crazyzhou — CHANGES_REQUESTED** [review]

File: src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java (hunk 1 above)
Comment (thekingofcity) [reply src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java]: fixed

**Review by crazyzhou — APPROVED** [review]
LGTM
