### PR TITLE
[issue-275] Fix breaking API changes introduced by Pravega watermark

### LINKED ISSUE #275: Fix breaking API changes introduced by Pravega watermark
**Problem description**
The fix from Pravega (pravega/pravega#4181) introduced breaking API changes to the connector component and it is causing the connector build to fail.

**Problem location**
Writer API

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by crazyzhou**
**Change log description**
- fix build error caused by API changes
- merge master

**Purpose of the change**
Fixes #275 

**What the code does**
Add writerId for writer and fix tests

**How to verify it**
`./gradlew clean build` passes.

### CODE REVIEW

File: src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java [hunk 1]
```diff
@@ -581,9 +581,11 @@ public void restoreState(List<PendingTransaction> pendingTransactionList) throws
 
                 try (
                         EventStreamClientFactory restoreClientFactory = createClientFactory(scope, clientConfig);
-                        TransactionalEventStreamWriter<T> restorePravegaWriter = restoreClientFactory.createTransactionalEventWriter(stream,
-                            eventSerializer,
-                            writerConfig);
+                        TransactionalEventStreamWriter<T> restorePravegaWriter =
+                                restoreClientFactory.createTransactionalEventWriter(name(),
```
Comment (maddisondavid) [inline src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java]: So just to confirm that THIS is the breaking change you refer to in that previously it did not require a `writerId`.

Comment (crazyzhou) [reply src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java]: Yes

**Comment by crazyzhou** [comment]
Cherry-picked it into the other two branches for Flink 1.7 and 1.8
