### PR TITLE
[Issue-380] Flink Job failing when using two readers on the same stream

### LINKED ISSUE #380: Flink Job failing when using two readers on the same stream
**Problem description**
When use more than one flink pravega reader on the same stream, the checkpoints do not seem to be resolving. The pravega checkpoints are completing, while the flink checkpoints are expiring. So, this might be a flink connector issue.

**Problem location**
Repo: https://github.com/dellThejas/video-samples/tree/5ea5515f73ac8e8df4679c654d173db2918bebae
File: video-samples/flinkprocessor/src/main/java/io/pravega/example/videoprocessor/TwoReaderSameStream.java

**Run instructions**
Run standalone pravega
Run configuration: 
- TwoReaderSameStream.java:
`--controller tcp://127.0.0.1:9090 --scope examples --input-stream face-detection-raw --output-stream face-detection-detected --badge-stream face-detection-raw --framesPerSec 1 --PRAVEGA_STANDALONE true --CAMERA 3 --akka.client.timeout 30000s --akka.ask.timeout 30000s --startAtTail true --readerParallelism 1 --parallelism 1 --checkpointIntervalMs 10000`

-CameraRecorder.java (video-samples/camera-recorder/src/main/java/io/pravega/example/camerarecorder/CameraRecorder.java):
`-DPRAVEGA_SCOPE="examples"
-DOUTPUT_STREAM_NAME="object-detector-input-video"
-DPRAVEGA_CONTROLLER_URI="tcp://10.243.37.188:9090"
-DIS_CREATE_SCOPE=false
-DCAMERA=3
-DCAMERA_DEVICE_NUMBER=0`

**Suggestions for an improvement**
I think this functionality needs to be included because this covers the use case when a flink job needs to access different stream cuts in the same stream at the same time.

**Log**
Part of the log that shows the issue

`INFO  [2020-06-03 15:05:43.526] [Legacy Source Thread - Source: input-source -> assignTimestampsAndWatermarks -> ChunkedVideoFrameReassembler (1/1)] i.p.c.s.impl.EventStreamReaderImpl: EventStreamReaderImpl( id=flink-task-Sourceinput-source-assignTimestampsAndWatermarks-ChunkedVideoFrameReassembler-1-1) at checkpoint PVG-CHK-1
INFO  [2020-06-03 15:05:43.545] [Legacy Source Thread - Source: input-source -> assignTimestampsAndWatermarks -> ChunkedVideoFrameReassembler (1/1)] i.p.c.s.impl.EventStreamReaderImpl: Reader flink-task-Sourceinput-source-assignTimestampsAndWatermarks-ChunkedVideoFrameReassembler-1-1 completed checkpoint PVG-CHK-1
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:32.876, frameNumber=683, tags=null, hash=[115, -59, -43, -121, -99, 58], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197390824-44684, position=examples/face-detection-raw/0.#epoch.0=197435508}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33280)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:33.904, frameNumber=684, tags=null, hash=[-47, -91, 63, -83, -8, 3], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197435508-45040, position=examples/face-detection-raw/0.#epoch.0=197480548}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33548)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:34.905, frameNumber=685, tags=null, hash=[19, -50, 51, -46, 97, -23], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197480548-45160, position=examples/face-detection-raw/0.#epoch.0=197525708}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33637)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:35.935, frameNumber=686, tags=null, hash=[30, -101, -5, -109, 69, -38], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197525708-45176, position=examples/face-detection-raw/0.#epoch.0=197570884}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33651)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:36.936, frameNumber=687, tags=null, hash=[123, 40, 67, -13, 98, -39], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197570884-44900, position=examples/face-detection-raw/0.#epoch.0=197615784}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33443)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:37.964, frameNumber=688, tags=null, hash=[56, 33, 89, 47, 51, -56], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197615784-44904, position=examples/face-detection-raw/0.#epoch.0=197660688}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33447)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:39.428, frameNumber=689, tags=null, hash=[-98, 109, -62, -27, -103, -9], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197660688-44560, position=examples/face-detection-raw/0.#epoch.0=197705248}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33188)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:40.428, frameNumber=690, tags=null, hash=[-57, -23, 123, 65, -8, 46], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197705248-44368, position=examples/face-detection-raw/0.#epoch.0=197749616}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(33044)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
VideoFrame{camera=3, ssrc=1646646410, timestamp=2020-06-03 15:05:41.46, frameNumber=691, tags=null, hash=[-88, -78, 89, 84, -40, -121], kittiSensorReadings=null, recognitions=[], sourceEventPointer=null, eventReadMetadata=EventReadMetadata{eventPointer=examples/face-detection-raw/0.#epoch.0:197749616-44288, position=examples/face-detection-raw/0.#epoch.0=197793904}, recognizedBoxes=[], embeddings=[], lastBadges=null, data(32985)=[-1, -40, -1, -32, 0, 16, 74, 70, 73, 70]}
[]
[]
[]
[]
[]
[]
[]
[]
[]
INFO  [2020-06-03 15:06:01.935] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Checkpoint 1 of job e5a22b3ec2139cdb7a8a0494c73d1ad4 expired before completing.
[]
[]
[]
[]
[]
[]
INFO  [2020-06-03 15:06:07.458] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Triggering checkpoint 2 @ 1591221967457 for job e5a22b3ec2139cdb7a8a0494c73d1ad4.
[]
[]
[]
[]
[]
[]
WARN  [2020-06-03 15:06:12.466] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Failed to trigger checkpoint 2 for job e5a22b3ec2139cdb7a8a0494c73d1ad4. (1 consecutive failed attempts so far)
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
	at io.pravega.connectors.flink.ReaderCheckpointHook.lambda$triggerCheckpoint$0(ReaderCheckpointHook.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[]
[]
[]
[]
[]
INFO  [2020-06-03 15:06:17.457] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Triggering checkpoint 3 @ 1591221977457 for job e5a22b3ec2139cdb7a8a0494c73d1ad4.
[]
[]
[]
[]
WARN  [2020-06-03 15:06:22.461] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Failed to trigger checkpoint 3 for job e5a22b3ec2139cdb7a8a0494c73d1ad4. (2 consecutive failed attempts so far)
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
	at io.pravega.connectors.flink.ReaderCheckpointHook.lambda$triggerCheckpoint$0(ReaderCheckpointHook.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[]
[]
[]
[]
[]
INFO  [2020-06-03 15:06:27.458] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Triggering checkpoint 4 @ 1591221987457 for job e5a22b3ec2139cdb7a8a0494c73d1ad4.
[]
[]
[]
[]
[]
WARN  [2020-06-03 15:06:32.461] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Failed to trigger checkpoint 4 for job e5a22b3ec2139cdb7a8a0494c73d1ad4. (3 consecutive failed attempts so far)
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
	at io.pravega.connectors.flink.ReaderCheckpointHook.lambda$triggerCheckpoint$0(ReaderCheckpointHook.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[]
[]
[]
[]
[]
INFO  [2020-06-03 15:06:37.459] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Triggering checkpoint 5 @ 1591221997458 for job e5a22b3ec2139cdb7a8a0494c73d1ad4.
WARN  [2020-06-03 15:06:37.459] [Checkpoint Timer] i.p.c.stream.impl.ReaderGroupImpl: Current outstanding checkpoints are : [PVG-CHK-2, PVG-CHK-3, PVG-CHK-4], maxOutstandingCheckpointRequest: 3, currentOutstandingCheckpointRequest: 3, errorMessage: rejecting checkpoint request since pending checkpoint reaches max allowed limit 3
WARN  [2020-06-03 15:06:37.459] [Checkpoint Timer] o.a.f.r.c.CheckpointCoordinator: Failed to trigger checkpoint 5 for job e5a22b3ec2139cdb7a8a0494c73d1ad4. (4 consecutive failed attempts so far)
org.apache.flink.util.FlinkException: Checkpoint master hook '-1642437961' produced an exception
	at org.apache.flink.runtime.checkpoint.hooks.MasterHooks.triggerHook(MasterHooks.java:176)
	at org.apache.flink.runtime.checkpoint.hooks.MasterHooks.triggerMasterHooks(MasterHooks.java:127)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.triggerCheckpoint(CheckpointCoordinator.java:631)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.triggerCheckpoint(CheckpointCoordinator.java:445)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator$ScheduledTrigger.run(CheckpointCoordinator.java:1323)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.MaxNumberOfCheckpointsExceededException: rejecting checkpoint request since pending checkpoint reaches max allowed limit
	at io.pravega.client.stream.impl.ReaderGroupImpl.initiateCheckpoint(ReaderGroupImpl.java:144)
	at io.pravega.connectors.flink.ReaderCheckpointHook.triggerCheckpoint(ReaderCheckpointHook.java:93)
	at org.apache.flink.runtime.checkpoint.hooks.MasterHooks$WrappedMasterHook.lambda$triggerCheckpoint$0(MasterHooks.java:374)
	at org.apache.flink.util.LambdaUtil.withContextClassLoader(LambdaUtil.java:97)
	at org.apache.flink.runtime.checkpoint.hooks.MasterHooks$WrappedMasterHook.triggerCheckpoint(MasterHooks.java:372)
	at org.apache.flink.runtime.checkpoint.hooks.MasterHooks.triggerHook(MasterHooks.java:153)
	... 11 common frames omitted
[]`

### PR DESCRIPTION
**Pull request by Guangfeng-Xu**
Signed-off-by: Guangfeng Xu <Guangfeng.Xu@dell.com>

**Change log description**
When use more than one flink pravega reader on the same stream, the checkpoints do not seem to be resolving. The pravega checkpoints are completing, while the flink checkpoints are expiring. The cause of the problem is that the same checkpoint hook identifiers among all the sources on same stream. The solution would be involve the reader group name in the hash function of the hookID. Then users can specify different name with `withReaderGroupName` method to have different IDs generated. Currently, the connector supports unspecified name for reader group, and then it will automatically generated a random name to be the RG name.

**Purpose of the change**
Fix #380

**What the code does**

1. Add a function isReaderGroupNameAutoGenerated(String readerGroupName) with regex check to check if the name is auto-generated.
2. In generateUid function, if isReaderGroupNameAutoGenerated(String readerGroupName) returns false, add readerGroupName to StringBuilder.
3. Add a new test case for the new generateUid function.

**How to verify it**
`./gradlew clean build` should pass

### CODE REVIEW

File: src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java [hunk 1]
```diff
@@ -507,6 +508,31 @@ public void testGenerateUid() {
...
+    public void testGenereateUidWithAutoGeneratedReaderGroupName() {
+        TestableStreamingReaderBuilder builder1 = new TestableStreamingReaderBuilder()
+                .withReaderGroupScope(SAMPLE_SCOPE)
+                .withReaderGroupName(GROUP_NAME)
+                .forStream(SAMPLE_STREAM, SAMPLE_CUT, StreamCut.UNBOUNDED);
+        String uid1 = builder1.generateUid();
+
+        TestableStreamingReaderBuilder builder2 = new TestableStreamingReaderBuilder()
+                .withReaderGroupScope(SAMPLE_SCOPE)
+                .withReaderGroupName("flink" + RandomStringUtils.randomAlphanumeric(20).toLowerCase())
```
Comment (crazyzhou) [inline src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java:521]: The test above have already covered the "random" name case because we are not specify the name. I think we don't need another test for this case. Instead, we should add a case with reader group name(just as `builder1 ` in this case) in the above test, and check if it's not equal to the others.

Comment (Guangfeng-Xu) [reply src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java:521]: This way of creating the `TestableStreamingReaderBuilder` doesn't create `readerGroupName` automatically, which means the `readerGroupName` is null. The test above doesn't cover the "random" name case. We don't specify the `readerGroupName` and the test case is ambiguous. I think merging the test case and the test case above is reasonable since specifying the `ReaderGrouName` is necessary in the test case.

Comment (crazyzhou) [reply src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java]: Yes, you are right, it's using the test builder.
